config/routes.rb
Rails.application.routes.draw do
  get 'pages/about'
  resources :charges 
  get 'charges/create'
  resources :line_items 
  resources :carts do 
    member do 
      post :pay  
    end 
  end
  resources :laptops



  resources :contacts, only: [:new, :create]
  get 'contacts/new'
  resources :searches
  resources :posts do 
  resources :show
  resources :comments


end


  devise_for :users, controllers: {

  	registrations: 'registrations'
  }
  root 'laptops#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/cart.rb
class Cart < ApplicationRecord



	has_many :line_items, dependent: :destroy 



	def add_laptop(laptop)
		current_item = line_items.find_by(laptop_id: laptop.id)
		
		if current_item
			current_item.increment(:quantity)
		else
			current_item = line_items.build(laptop_id: laptop.id)
		end
		current_item
	end

	def total_price
		line_items.to_a.sum{ |item| item.total_price}
	end


end

app/controllers/carts_controller.rb
class CartsController < ApplicationController

  rescue_from ActiveRecord::RecordNotFound, with: :invalid_cart
  before_action :set_cart, only: [:show, :edit, :update, :destroy]



  # GET /carts
  # GET /carts.json
  def index
    @carts = Cart.all
  end

  # GET /carts/1
  # GET /carts/1.json
  def show
  
  end

  def pay 
      @cart = Cart.find(params[:id])
    
       amount = (@cart.total_price * 100).to_i
      # Set your secret key: remember to change this to your live secret key in production
      # See your keys here: https://dashboard.stripe.com/account/apikeys
      Stripe.api_key = ""

      # Token is created using Checkout or Elements!
      # Get the payment token ID submitted by the form:
       @customer = Stripe::Customer.create(email: params[:Email],
                                          source: params[:Token])



   
      @charge = Stripe::Charge.create(
        customer: @customer.id,
          :amount => amount,
          :currency => 'eur',
          
          :description => 'Payment for card #{@cart.id}'
          
      )

      if charge.paid && charge.amount == amount 
        cart = Cart.create()
      end
      
          rescue Stripe::CardError => e
          
        #redirect_to @cart, notice: "Payment declined" and return
     
    
      @cart.update(status: "Sold")
      session.delete(:cart_id)
      redirect_to root_path, notice: "The laptop is on it's way" 
  end






  # GET /carts/new
  def new
    @cart = Cart.new
  end

  # GET /carts/1/edit
  def edit
  end

  # POST /carts
  # POST /carts.json
  def create
    @cart = Cart.new(cart_params)

    respond_to do |format|
      if @cart.save
        format.html { redirect_to @cart, notice: 'Cart was successfully created.' }
        format.json { render :show, status: :created, location: @cart }
      else
        format.html { render :new }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /carts/1
  # PATCH/PUT /carts/1.json
  def update
    respond_to do |format|
      if @cart.update(cart_params)
        format.html { redirect_to @cart, notice: 'Cart was successfully updated.' }
        format.json { render :show, status: :ok, location: @cart }
      else
        format.html { render :edit }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /carts/1
  # DELETE /carts/1.json
  def destroy
    @cart.destroy if @cart.id == session[:cart_id]
    session[:cart_id] = nil
    respond_to do |format|
      format.html { redirect_to root_path, notice: 'Cart was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cart
      @cart = Cart.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cart_params
      params.fetch(:cart, {})
     
    end

    def invalid_cart
      logger.error "Attempt to access invalid cart #{params[:id]}"
      redirect_to root_path, notice: "That cart doesn't exist"
    end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/_form.html.erb
<%= simple_form_for(@cart)  do |f|   %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs" >
  </div>

  <div class="form-actions"  >
    <%= f.button :submit %>
  </div>
<% end %>

app/views/carts/_payment.html.erb
<% if !@cart.persisted? %>
  <h4 class="subtitle is-4">Payment</h4>

  <div class="notification is-light has-text-centered">
    <i class="fa fa-credit-card"></i>
    All Laptop cost <strong><%= @cart.total_price * 100 %></strong> Euros. 
    <span class="block mb4"></span>
  </div>

  <div class="form-row">
    <label for="card-element" class="label">
      Enter credit or debit card
    </label>

    <div id="card-element" class="form-control">
      <!-- a Stripe Element will be inserted here. -->
    </div>
    <!-- used to display Element errors -->
    <div id="card-errors" role="alert"></div>
  </div>

  <% if current_user.stripe_id.present? %>
    <div class="last-card bg-light pa4 border-radius-3 mt4">
      <h5 class="is-6 title pt2">Previously used card</h5>
      <table class="table is-narrow bg-light is-fullwidth">
        <thead>
          <th>Card Brand</th>
          <th>Last 4 Digits</th>
          <th>Expiration Month</th>
          <th>Expiration Year</th>
        </thead>
        <tr>
          <td><%= current_user.card_brand %></td>
          <td><%= current_user.card_last4 %></td>
          <td><%= current_user.card_exp_month %></td>
          <td><%= current_user.card_exp_year %></td>
        </tr>
      </table>
    </div>
  <% end %>
<% end %>

app/views/carts/edit.html.erb
<h1>Editing Cart</h1>

<%= render 'form', cart: @cart %>

<%= link_to 'Show', @cart %> |
<%= link_to 'Back', carts_path %>

app/views/carts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Carts</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @carts.each do |cart| %>
      <tr>
        <td><%= link_to 'Show', cart %></td>
        <td><%= link_to 'Edit', edit_cart_path(cart) %></td>
        <td><%= link_to 'Destroy', cart, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cart', new_cart_path %>

app/views/carts/new.html.erb
<h1>New Cart</h1>

<%= render 'form', cart: @cart  %>

<%= link_to 'Back', carts_path %>

app/views/carts/show.html.erb
<% content_for :header do %>
<section class="hero is-warning">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        Browse the latest laptop on our community
      </h1>
    </div>
  </div>
</section>
<% end %>



<div class="keep-shopping pv1 mt4 has-text-right">


  <%= link_to 'Keep Shopping', laptops_path, class: 'button is-warning' %>
</div>
<hr />
<section class="section">
  <%= render(@cart.line_items) %>

  <div class="columns">
    <div class="column">
      <%= button_to 'Empty Cart', @cart, method: :delete, data: { confirm: "Are you sure? " }, class: "button is-danger" %>
    </div>
    <div class="column total has-text-right">
      <h4 class="title is-4">
        <span class="f5 has-text-grey">Total:</span> <%= number_to_currency(@cart.total_price, :unit => ' €') %>
      </h4>

    </div>



 </div>
  </div>

 
</section>

 
    


     




 