config/routes.rb
Rails.application.routes.draw do
  get 'pages/about'
  resources :charges 
  get 'charges/create'
  resources :line_items 
  resources :carts do 
    member do 
      post :pay  
    end 
  end
  resources :laptops



  resources :contacts, only: [:new, :create]
  get 'contacts/new'
  resources :searches
  resources :posts do 
  resources :show
  resources :comments


end


  devise_for :users, controllers: {

  	registrations: 'registrations'
  }
  root 'laptops#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/laptop.rb
class Laptop < ApplicationRecord

	before_destroy :not_referenced_by_any_line_item

	belongs_to :user, optional:true

	has_many :line

	mount_uploader :image, ImageUploader
	serialize :image, JSON                #if you use sqlite, add this line

	


	validates :title, :brand, :price, :model, presence: true
 
	validates :description, length: { maximum: 1000, too_long: "%{count} characters is the maximum allowed. " }

	validates :title, length: { maximum: 140, too_long: "%{count} characters is the maximum allowed. " }

	validates :price, length: { maximum: 7 }

  BRAND = %w{ Dell MacBook Asus Lenovo HP Toshiba "blank" }
  FINISH = %w{ Black White Navy Blue Red Clear Satin Yellow Seafoam }
  CONDITION = %w{ New Excellent Mint Used Fair Poor }

  private 
  	def not_referenced_by_any_line_item
  		unless line_items.empty?
  			errors.add(:base, "Line items present")
  			throw :abort

       end
   end


   def self.search(search)
   	if search
   		where(["brand LIKE ?", "%#{search}%"])

   	else
   		all
   	end
   end


end

app/controllers/laptops_controller.rb
class LaptopsController < ApplicationController
  before_action :set_laptop, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  # GET /laptops
  # GET /laptops.json
  def index
    @laptops = Laptop.all.order("created_at desc")
    @laptops = Laptop.search(params[:search])

    #@laptops = Laptop.where(["name LIKE ? ", "%#{params[:search]}%"])
  end
  #brand, :model, :description, :condition, :finish, :title, :price, :image)

  # GET /laptops/1
  # GET /laptops/1.json
  def show
  end

  # GET /laptops/new
  def new
    @laptop = current_user.laptops.build
  end

  # GET /laptops/1/edit
  def edit
  end

  # POST /laptops
  # POST /laptops.json
  def create
    @laptop = current_user.laptops.build(laptop_params)

     
    respond_to do |format|
      if @laptop.save
        format.html { redirect_to @laptop, notice: 'Laptop was successfully created.' }
        format.json { render :show, status: :created, location: @laptop }
      else
        format.html { render :new }
        format.json { render json: @laptop.errors, status: :unprocessable_entity }
      end
    end


   
  end

  # PATCH/PUT /laptops/1
  # PATCH/PUT /laptops/1.json
  def update
    respond_to do |format|
      if @laptop.update(laptop_params)
        format.html { redirect_to @laptop, notice: 'Laptop was successfully updated.' }
        format.json { render :show, status: :ok, location: @laptop }
      else
        format.html { render :edit }
        format.json { render json: @laptop.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /laptops/1
  # DELETE /laptops/1.json
  def destroy
    @laptop.destroy
    respond_to do |format|
      format.html { redirect_to laptops_url, notice: 'Laptop was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

    private
    # Use callbacks to share common setup or constraints between actions.
    def set_laptop
      @laptop = Laptop.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def laptop_params
      params.require(:laptop).permit(:brand, :model, :description, :condition, :finish, :title, :price, :image)

    end
  end 

app/helpers/laptops_helper.rb
module LaptopsHelper

	def laptop_author(laptop)
		user_signed_in? && current_user.id == laptop.user_id
	end
end

app/views/laptops/_form.html.erb
<div class="columns">
  <div class="column is-8 is-centered">

    <%= simple_form_for @laptop,  html: { multipart: true } do |f| %>
      <%= f.error_notification %>

        <div class="columns">

          <div class="field column is-9">
            <div class="control">
              <%= f.input :title , required: true, input_html: { class: "input"}, wrapper: false, label_html: { class:"label" } %>
            </div>
          </div>

          <div class="field column">
            <div class="control">
              <%= f.input :price, required: true, input_html: { class:"input", maxlength: 7  }, wrapper: false, label_html: { class:"label" } %>
            </div>
          </div>

        </div>

        <div class="field">
          <div class="control">
            <%= f.input :model, required: true, input_html: { class:"input" }, wrapper: false, label_html: { class:"label" } %>
          </div>
        </div>

        <div class="field">
          <div class="control">
            <%= f.input :description, required: true, input_html: { class:"textarea" }, wrapper: false, label_html: { class:"label" } %>
          </div>
        </div>

        <div class="columns">
          <div class="field column is-4">
            <div class="control">
              <label class="label">Brand</label>
              <div class="control has-icons-left">
                <span class="select">
                  <%= f.input_field :brand, collection: Laptop::BRAND, prompt: "Select brand" %>
                </span>
                <span class="icon is-small is-left">
                  <i class="fa fa-tag"></i>
                </span>
              </div>
            </div>
           </div>

          <div class="field column is-4">
            <div class="control">
              <label class="label">Finish</label>
              <div class="control has-icons-left">
                <span class="select">
                  <%= f.input_field :finish, collection: Laptop::FINISH, prompt: "Select finish" %>
                </span>
                <span class="icon is-small is-left">
                  <i class="fa fa-paint-brush"></i>
                </span>
              </div>
            </div>
           </div>

          <div class="field column is-4">
            <div class="control">
              <label class="label">Condition</label>
              <div class="control has-icons-left">
                <span class="select">
                  <%= f.input_field :condition, collection: Laptop::CONDITION, prompt: "Select condition" %>
                </span>
                <span class="icon is-small is-left">
                  <i class="fa fa-paint-brush"></i>
                </span>
              </div>
            </div>
           </div>
         </div>

        <div class="field">
          <div class="control">
            <label class="label">Add images</label>
              <div class="file">
              <label class="file-label">
                <%= f.input :image, as: :file, input_html: { class:"file-input laptop-image" }, label: false, wrapper: false %>
                  <span class="file-cta">
                    <span class="file-icon"><i class="fa fa-upload"></i></span>
                    <span class="file-label">Choose a file…</span>
                  </span>
              </label>
              </div>
            </div>
          </div>
          <output id="list"></output>
        <hr />

        <div class="field is-grouped">
          <div class="control">
            <%= f.button :submit, class: 'button is-warning' %>
            <%= link_to 'Cancel', laptops_path, class:'button is-light' %>
          </div>
        </div>

      <% end %>
  </div>
</div>

app/views/laptops/edit.html.erb
<% content_for :header do %>
<section class="hero is-warning">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
       Editing  Laptop
      </h1>
    </div>
  </div>
</section>
<% end %>

<div class="pv4">
  <%= render 'form', laptop: @laptop %>
</div>

app/views/laptops/index.html.erb
<% content_for :header do %>
<section class="hero is-warning">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        Browse the latest laptop on our community
      </h1>
    </div>
  </div>
</section>
<% end %>

<%= form_tag laptops_path, :method => 'get' do %>
<%= text_field_tag :search, params[:search], placeholder: "dell,hp,macbook" %>
<%= submit_tag "Search" %>
<% end %>
<%= link_to "Advanced Search", new_search_path %>

<div class="laptop-index-grid pt4">
  <% @laptops.each do |laptop| %>

    <div class="laptop border-light">
      <div class="laptop-thumb">
    




 <%= link_to image_tag(laptop.image_url(:thumb)), laptop %>



      <% if laptop.condition? %>
        <div class="condition">
          <span class="tag is-dark"><%= laptop.condition %></span>
        </div>
      <% end %>
      </div>


    <div class="pa3">

      <h3 class="fw7 f4 title"><%= link_to laptop.title, laptop %></h3>

     <p class="has-text-gray fg pt1">For sale <%= laptop.user.email.split('@').first %></p>

      <p class="f3 fw6 has-text-right pt2 price"><%= number_to_currency(laptop.price, :unit => "€ ") %></p>

      <% if laptop_author(laptop) %>
         <%= link_to 'Edit', edit_laptop_path(laptop), class: "button is-small" %>
         <%= link_to 'Delete', laptop, method: :delete, data: { confirm: "Are you sure ?" }, class: "button is-small" %>
      <% end %>

    </div>
  </div>
<% end %>
</div>

app/views/laptops/new.html.erb
<% content_for :header do %>
<section class="hero is-warning">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        Sell an Laptop
      </h1>
    </div>
  </div>
</section>
<% end %>

<div class="pv4">
  <%= render 'form', laptop: @laptop %>
</div>

app/views/laptops/show.html.erb
<% content_for :header do %>
<section class="hero is-warning">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        Browse the latest laptop on our community
      </h1>
    </div>
  </div>
</section>
<% end %>



<% content_for :body_class, 'bg-light' %>

<section class="section laptop-show">
  
  <dir class="columns">
      
      <div class="column is-8">
        <h1 class="title is-2"> <%= @laptop.title  %></h1>
      
      <ul class="pv1">

          <% if @laptop.brand?  %>
          <li class="inline-block pr3"> <%= @laptop.brand %></li>
        <% end %>  

         <% if @laptop.model?  %>
          <li class="inline-block pr3"> <%= @laptop.model %></li>
        <% end %>  

         <% if @laptop.condition?  %>
          <li class="inline-block pr3"> <%= @laptop.condition %></li>
        <% end %>  

      </ul>


      <div class="feature-image">
      
        <%= image_tag(@laptop.image_url(:default)) %>
      </div>

      <div class="content pa4 mt3 bg-white border-radius-3">

      <h3 class="subtitle is-4 ">Description</h3>

        <%= @laptop.description %>
        

      <h3 class="subtitle is-4 pt2">Product Specs</h3>

      <table class="table is-narrow">
        
          <% if @laptop.condition %>
        <tr>
          <td class="has-text-weight-bold">Condition:</td>
          <td><%= @laptop.condition %></td>
        </tr>
        <% end %>

        <% if @laptop.finish %>
          <tr>
            <td class="has-text-weight-bold">Finish:</td>
            <td><%= @laptop.finish %></td>
          </tr>
        <% end %>

        <% if @laptop.brand %>
          <tr>
            <td class="has-text-weight-bold">Brand:</td>
            <td><%= @laptop.brand %></td>
          </tr>
        <% end %>

        <tr>
          <td class="has-text-weight-bold">Model:</td>
          <td><%= @laptop.model %></td>
        </tr>

      </table>
    </div>
    </div>
    <div class="column is-3 is-offset-1">
      <div class="bg-white pa4 border-radius-3">
        <h4 class="title is-5 has-text-centered"><%= number_to_currency(@laptop.price, :unit => ' €') %></h4>
        <p class="has-text-centered mb4">For Sale by <%= @laptop.user.email.split('@').first %></p>
        <%= button_to 'Add to cart', line_items_path(laptop_id: @laptop), class: 'button is-warning add-to-cart' %>
      </div>
    </div>
  </div>

  <% if laptop_author(@laptop) %>
    <%= link_to 'Edit', edit_laptop_path(@laptop), class: 'button' %>
  <% end %>
</section>