config/routes.rb
Rails.application.routes.draw do
  get 'pages/about'
  resources :charges 
  get 'charges/create'
  resources :line_items 
  resources :carts do 
    member do 
      post :pay  
    end 
  end
  resources :laptops



  resources :contacts, only: [:new, :create]
  get 'contacts/new'
  resources :searches
  resources :posts do 
  resources :show
  resources :comments


end


  devise_for :users, controllers: {

  	registrations: 'registrations'
  }
  root 'laptops#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord



	has_many :line_items, dependent: :destroy 



	def add_laptop(laptop)
		current_item = line_items.find_by(laptop_id: laptop.id)
		
		if current_item
			current_item.increment(:quantity)
		else
			current_item = line_items.build(laptop_id: laptop.id)
		end
		current_item
	end

	def total_price
		line_items.to_a.sum{ |item| item.total_price}
	end


end

app/models/comment.rb
class Comment < ApplicationRecord


	belongs_to :post
	
end

app/models/contact.rb
class Contact < MailForm::Base

	attribute :name,     :validate => true
	attribute :email,    :validate =>  /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/
    attribute :message,  :validate => true
    attribute :nickname, :captcha => true


    def headers
    	{

    	:subject => "Contact Form",
        :to => "warlins25@gmail.com",
        :from => %("#{name}" <#{email}>)

        }
	end

end 

app/models/current_cart.rb
module CurrentCart

	private 

	def set_cart
		@cart = Cart.find(session[:cart_id])
	rescue ActiveRecord::RecordNotFound

		@cart = Cart.create
		session[:cart_id] = @cart.id
	end
end

app/models/laptop.rb
class Laptop < ApplicationRecord

	before_destroy :not_referenced_by_any_line_item

	belongs_to :user, optional:true

	has_many :line

	mount_uploader :image, ImageUploader
	serialize :image, JSON                #if you use sqlite, add this line

	


	validates :title, :brand, :price, :model, presence: true
 
	validates :description, length: { maximum: 1000, too_long: "%{count} characters is the maximum allowed. " }

	validates :title, length: { maximum: 140, too_long: "%{count} characters is the maximum allowed. " }

	validates :price, length: { maximum: 7 }

  BRAND = %w{ Dell MacBook Asus Lenovo HP Toshiba "blank" }
  FINISH = %w{ Black White Navy Blue Red Clear Satin Yellow Seafoam }
  CONDITION = %w{ New Excellent Mint Used Fair Poor }

  private 
  	def not_referenced_by_any_line_item
  		unless line_items.empty?
  			errors.add(:base, "Line items present")
  			throw :abort

       end
   end


   def self.search(search)
   	if search
   		where(["brand LIKE ?", "%#{search}%"])

   	else
   		all
   	end
   end


end

app/models/line_item.rb
    class LineItem < ApplicationRecord
  belongs_to :laptop
  belongs_to :cart
  
  

  def total_price
  	laptop.price.to_i * quantity.to_i
  end

end

app/models/post.rb
class Post < ApplicationRecord
	
	belongs_to :user
	has_many :comments


	mount_uploader :image, ImageUploader

	mount_uploader :image, ImageUploader
	serialize :image, JSON   #if you sqllite add this line

	#belongs_to :user, optional:true

	validates :title, :content,  presence: true

	validates :title, length: { maximum: 140, too_long: "%{count} characters is the maximum allowed. " }


end

app/models/search.rb
class Search < ApplicationRecord

		def search_laptops

		laptops = Laptop.all



  		laptops = laptops.where(["keywords LIKE ?", "%#{keywords}%"]) if keywords.present?
  		laptops = laptops.where(["brand LIKE ?", brand]) if brand.present?
  		laptops = laptops.where(["title LIKE ?", title]) if title.present?
  		laptops = laptops.where(["price >= ?", min_price]) if min_price.present?
  		laptops = laptops.where(["price <= ?", max_price]) if max_price.present?
   		laptops = laptops.where(["condition LIKE ?", condition]) if condition.present?
    	laptops = laptops.where(["finish LIKE ?", finish]) if finish.present?

    	return laptops
  
end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


         has_many :laptops
         has_many :posts
         has_many :comments
        
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/laptops_helper.rb
module LaptopsHelper

	def laptop_author(laptop)
		user_signed_in? && current_user.id == laptop.user_id
	end
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper

	def post_author(post)
		user_signed_in? && current_user.id == post.user_id
	end
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/store_helper.rb
module StoreHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Computer Store</title>
    <%= csrf_meta_tags %>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag 'https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css' %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  


        <%= javascript_include_tag 'application' %>
    <%= javascript_include_tag 'https://js.stripe.com/v1/', 'application' %>

     <%= javascript_include_tag 'application', "https://js.stripe.com/v2/", "https://js.stripe.com/v3/", 'data-turbolinks-track': 'reload' %>

    <%= tag :meta, name: "stripe-public-key", content: Figaro.env.stripe_publishable_key %>


    <%= csrf_meta_tags  %>
  
  </head>

  <body class="<%= yield (:body_class) %>">
    <% if flash[:notice] %>
      <div class="notification is-success global-notification">
        <p class="notice"><%= notice %></p>
      </div>
    <% end %>
    <% if flash[:alert] %>
    <div class="notification is-danger global-notification">
      <p class="alert"><%= alert %></p>
    </div>
    <% end %>
    <nav class="navbar is-warning" role="navigation" aria-label="main navigation">
  <div class="navbar-brand">
     <%= link_to root_path, class:"navbar-item" do %>
      <h1 class="title is-5">Laptop Store</h1>
        <% end  %>


    <a role="button" class="navbar-burger burger " aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
    </a>
  </div>



  <div id="navbarBasicExample" class="navbar-menu">
    <div class="navbar-start">
      <%= link_to "Home", root_path, class:"navbar-item" %>

     
            <%= link_to "Blog", posts_path, class: "navbar-item"%>
           
         
           <%= link_to "About us", pages_about_path, class: "navbar-item"%>
         

          
           <%= link_to "Contact", contacts_new_path, class: "navbar-item"%>
        

           <%= link_to 'Sell', new_laptop_path, class: "navbar-item" %>


      <div class="navbar-item ">

         <% if total_cart_items %>
              <%= link_to cart_path(@cart), class:"navbar-item " do %>
              <span class="icon is-small">
                <i class="fa fa-shopping-cart"></i>
              </span>
              <span>Cart
                <%= cart_count_over_one %>
                </span>
              <% end %>
            <% end %>

        <% if user_signed_in? %>

             
              <div class="navbar-item has-dropdown is-hoverable">
                <%= link_to 'Account', edit_user_registration_path, class: "navbar-link" %>
                <div class="navbar-dropdown is-right">
                  <%= link_to current_user.email, edit_user_registration_path, class:"navbar-item" %>
                  <%= link_to "Log Out", destroy_user_session_path, method: :delete, class:"navbar-item" %>
                </div>
              </div>
            <% else %>

            <%= link_to "Sign In", new_user_session_path, class: "button  is-small is-info  " %> &nbsp
            <%= link_to "Sign up", new_user_registration_path, class:"button  is-small is-info"%>

            <% end %>
            
        </div>
      </div>
    </div>
  </div>
</nav>

  <%= yield(:header) %>

  <div class="container">

    <%= yield %>

  </div>

  <footer class="footer">
  <div class="content has-text-centered">
    
    <p>Andre, Sibusiso, Warley</a>. College Project - Ecommerce
      <a href="#">MIT</a>. The website content
      is licensed <a href="#">NCI - College</a>
    

<p>
  <a class="button">
    <span class="icon">
      <i class="fab fa-github"></i>
    </span>
    <span>GitHub</span>
  </a>
  <a class="button">
    <span class="icon">
      <i class="fab fa-twitter"></i>
    </span>
    <span>Twitter</span>
  </a>

  <a class="button">
    <span class="icon">
      <i class="fab fa-twitter"></i>
    </span>
    <span>Facebook</span>
  </a>
  
  
  
</p>
  
  </div>
</footer>

<script defer src="https://use.fontawesome.com/releases/v5.3.1/js/all.js"></script>

  </body>

</html>

app/views/pages/about.html.erb
 <% content_for :header do %>
<section class="hero is-warning">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        About us
      </h1>
    </div>
  </div>
</section>
<% end %>

 
      <div class="section-heading has-text-centered pv5">
        <h3 class="title is-2 has">About the Laptop Store</h3>
        <span class="elementor-divider-separator"></span>
        <p class="subtitle is-6 ">Here at laptopstorek we are passionate about what we do. We help many customers to sell their laptops daily and have strict procedures in place to securely in their orders, If you are looking for someone to sell your laptop too then contact one of the team today.  </p>
      </div>
      <br>

                <div class="columns is-centered pv5 ">
                    <div class="column is-5">
                        <figure class="image is-4by3 ">
                            <img src="https://picsum.photos/800/600/?random" alt="Description">
                        </figure>
                    </div>
                    <div class="column is-5 is-offset-1">
                        <h1 class="title is-3">
                            We are passionte for laptop
                        </h1>
                        <h2 class="subtitle is-6">
                            We can help you choose the right Laptop just by taking a few search on our website.
                        </h2>
                        <br>
                        
                    </div>
         
     </div>